name: Build recovery on macos

on:
  workflow_dispatch:
     inputs:
      MANIFEST:
        description: 'manifest'
        required: true
        default: 'https://github.com/Huexxx/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'branch'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE:
        description: 'device tree'
        required: true
        default: 'https://github.com/Huexxx/twrp_device_xiaomi_chiron'
      DEVICE_TREE_BRANCH:
        description: 'branch'
        required: true
        default: '13'
      DEVICE_PATH:
        description: 'device path'
        required: true
        default: 'device/xiaomi/chiron'
      DEVICE_NAME:
        description: 'device codename'
        required: true
        default: 'chiron'
      MAKEFILE_NAME:
        description: 'makefile name'
        required: true
        default: 'twrp_chiron'
      MAKEWHAT:
        description: 'make what'
        required: true
        default: 'recovery'
        
jobs:
  Build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: macos-10.15

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        ulimit -S -n 2048
        hdiutil create ~/android.dmg -volname "android" -size 85G -fs "Case-sensitive HFS+"
        hdiutil mount ~/android.dmg
        mkdir -p ${GITHUB_WORKSPACE}/workspace
        ln -s /Volumes/android ${GITHUB_WORKSPACE}/workspace

    - name: Init Repo
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo > ~/bin/repo
        chmod a+x ~/bin/repo
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        ~/bin/repo init --depth=1 -u ${{ github.event.inputs.MANIFEST }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        
    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        ~/bin/repo sync -j4
  
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        
    - name: Building debugfs_static-host
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        . build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        mka ${{ github.event.inputs.MAKEWHAT }}image

    - name: Generate info
      run: |
        cd ${GITHUB_WORKSPACE}/workspace/android
        wget https://raw.githubusercontent.com/xiaoleGun/build_recovery_action/main/get_info.sh
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        bash get_info.sh ${{ github.event.inputs.DEVICE_NAME }} ${{ github.event.inputs.MAKEWHAT }}

    - name: Upload to Release...
      uses: ncipollo/release-action@v1.8.0
      with:
        artifacts: workspace/android/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
        name: ${{ env.RECOVERYISWHAT }}_${{ github.event.inputs.DEVICE_NAME }}_${{ env.BUILD_TIME }}
        tag: ${{ github.event.inputs.DEVICE_NAME }}_${{ env.BUILD_TIME }}
        bodyFile: workspace/info.txt
        token: ${{ secrets.GITHUB_TOKEN }}
